#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'nodejs', '~> 2.0.0'
cookbook 'postgresql'
cookbook 'redis2', '~> 0.5.0'
cookbook 'nginx', '~> 2.7.4'
cookbook 'screen', '~> 0.8.0'